version: '3.8'

services:
  edgedb:
    image: edgedb/edgedb:latest
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
    ports:
      - "5656:5656"
    volumes:
      - edgedb_data:/var/lib/edgedb/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: banking
      RABBITMQ_DEFAULT_PASS: banking123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  banking-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      CLIENT_ID: ${CLIENT_ID:-default}
      EDGEDB_HOST: edgedb
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - edgedb
      - redis
      - rabbitmq
    volumes:
      - ./src:/app/src

volumes:
  edgedb_data:
  redis_data:
  rabbitmq_data: 